"""Initial schema - 8 tables

Revision ID: 8aee8d7a4035
Revises: 
Create Date: 2025-12-08 12:13:25.170770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8aee8d7a4035'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('subtasks', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_created_at'), 'template', ['created_at'], unique=False)
    op.create_index(op.f('ix_template_name'), 'template', ['name'], unique=False)
    op.create_table('activitylog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('CREATED', 'UPDATED', 'COMPLETED', 'DELETED', 'RESTORED', name='actiontype'), nullable=False),
    sa.Column('field_changed', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('old_value', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('new_value', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activitylog_action_type'), 'activitylog', ['action_type'], unique=False)
    op.create_index(op.f('ix_activitylog_created_at'), 'activitylog', ['created_at'], unique=False)
    op.create_index(op.f('ix_activitylog_task_id'), 'activitylog', ['task_id'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('ocr_text', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_created_at'), 'attachment', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachment_task_id'), 'attachment', ['task_id'], unique=False)
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_created_at'), 'note', ['created_at'], unique=False)
    op.create_index(op.f('ix_note_task_id'), 'note', ['task_id'], unique=False)
    op.create_table('subtask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtask_display_order'), 'subtask', ['display_order'], unique=False)
    op.create_index(op.f('ix_subtask_task_id'), 'subtask', ['task_id'], unique=False)
    op.alter_column('chatmessage', 'role',
               existing_type=sa.VARCHAR(length=10),
               type_=sqlmodel.sql.sqltypes.AutoString(length=20),
               existing_nullable=False)
    op.alter_column('chatmessage', 'content',
               existing_type=sa.VARCHAR(length=5000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10000),
               existing_nullable=False)
    op.alter_column('chatmessage', 'language',
               existing_type=sa.VARCHAR(length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_chatmessage_created_at'), 'chatmessage', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatmessage_language'), 'chatmessage', ['language'], unique=False)
    op.add_column('task', sa.Column('display_order', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('is_template', sa.Boolean(), nullable=False))
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=200),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=2000),
               type_=sqlmodel.sql.sqltypes.AutoString(length=5000),
               nullable=True)
    op.alter_column('task', 'priority',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'),
               existing_nullable=False)
    op.alter_column('task', 'tags',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=1000),
               nullable=True)
    op.create_index(op.f('ix_task_created_at'), 'task', ['created_at'], unique=False)
    op.create_index(op.f('ix_task_display_order'), 'task', ['display_order'], unique=False)
    op.create_index(op.f('ix_task_is_template'), 'task', ['is_template'], unique=False)
    op.add_column('voicecommand', sa.Column('intent', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('voicecommand', sa.Column('confidence', sa.Float(), nullable=True))
    op.alter_column('voicecommand', 'transcript',
               existing_type=sa.VARCHAR(length=500),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=False)
    op.alter_column('voicecommand', 'language',
               existing_type=sa.VARCHAR(length=5),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.create_index(op.f('ix_voicecommand_created_at'), 'voicecommand', ['created_at'], unique=False)
    op.create_index(op.f('ix_voicecommand_language'), 'voicecommand', ['language'], unique=False)
    op.drop_column('voicecommand', 'success')
    op.drop_column('voicecommand', 'action')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voicecommand', sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('voicecommand', sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_voicecommand_language'), table_name='voicecommand')
    op.drop_index(op.f('ix_voicecommand_created_at'), table_name='voicecommand')
    op.alter_column('voicecommand', 'language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('voicecommand', 'transcript',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('voicecommand', 'confidence')
    op.drop_column('voicecommand', 'intent')
    op.drop_index(op.f('ix_task_is_template'), table_name='task')
    op.drop_index(op.f('ix_task_display_order'), table_name='task')
    op.drop_index(op.f('ix_task_created_at'), table_name='task')
    op.alter_column('task', 'tags',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=1000),
               type_=sa.VARCHAR(length=500),
               nullable=False)
    op.alter_column('task', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('task', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=5000),
               type_=sa.VARCHAR(length=2000),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('task', 'is_template')
    op.drop_column('task', 'display_order')
    op.drop_index(op.f('ix_chatmessage_language'), table_name='chatmessage')
    op.drop_index(op.f('ix_chatmessage_created_at'), table_name='chatmessage')
    op.alter_column('chatmessage', 'language',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('chatmessage', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10000),
               type_=sa.VARCHAR(length=5000),
               existing_nullable=False)
    op.alter_column('chatmessage', 'role',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_index(op.f('ix_subtask_task_id'), table_name='subtask')
    op.drop_index(op.f('ix_subtask_display_order'), table_name='subtask')
    op.drop_table('subtask')
    op.drop_index(op.f('ix_note_task_id'), table_name='note')
    op.drop_index(op.f('ix_note_created_at'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_attachment_task_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_created_at'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_activitylog_task_id'), table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_created_at'), table_name='activitylog')
    op.drop_index(op.f('ix_activitylog_action_type'), table_name='activitylog')
    op.drop_table('activitylog')
    op.drop_index(op.f('ix_template_name'), table_name='template')
    op.drop_index(op.f('ix_template_created_at'), table_name='template')
    op.drop_table('template')
    # ### end Alembic commands ###
